### ISSUE TITLE
How do I configure with Librechat? 

### ISSUE THREAD

**Issue by parthpat12** [acehoss/mcp-gateway#1]
Have LibreChat running inside docker. How do I setup this gateway inside LibreChat.yaml file?

**Comment by acehoss** [comment]
The entries in `librechat.yaml` follow the "everything" example:

```yaml
mcpServers:
  filesystem:
    url: http://10.0.2.221:3000/filesystem
  puppeteer:
    url: http://10.0.2.221:3000/puppeteer
  youtube:
    url: http://10.0.2.221:3000/youtube
  line-editor:
    url: http://10.0.2.221:3000/line-editor
  thinking:
    url: http://10.0.2.221:3000/thinking
```
You could use `host.docker.internal` if you set that up. I used the network IP of the host mostly out of laziness.

And this is my mcp-gateway `config.yaml`:
*Note*: I'm running many of these from source rather than `npx` because they either required tweaks to work with LibreChat (like the youtube transcript server) or I wanted to add some extra functionality.

```yaml
hostname: "0.0.0.0"  # Listen on all interfaces by default
port: 3000

# Debug configuration (optional)
debug:
  level: "info"  # Possible values: "error", "warn", "info", "debug", "verbose"

# Authentication configuration (optional)
# auth:
#   basic:
#     enabled: true
#     credentials:
#       - username: "admin"
#         password: "your-secure-password"
#   bearer:
#     enabled: true
#     tokens:
#       - "your-secure-token"

servers:
  filesystem:
    command: tsx
    args:
      - "/home/aaron/AI/MCP-Servers/src/filesystem/index.ts"
      - "/home/aaron/Clara"

  puppeteer:
    command: tsx
    args:
      - "/home/aaron/AI/MCP-Servers/src/puppeteer/index.ts"

  thinking:
    command: tsx
    args:
      - "/home/aaron/AI/MCP-Servers/src/sequentialthinking/index.ts"
  
  youtube:
    command: tsx
    args:
      - "/home/aaron/AI/mcp-server-youtube-transcript/src/index.ts"

  line-editor:
    command: /home/aaron/.local/bin/uvx
    args:
      - "mcp-text-editor"
```

**Comment by michnovka** [comment]
I am running this on my server which is headless, and I had constant errors while trying to run puppeteer using npx.

In the end, I [found in the documentation](https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer#docker) you can use docker. So I ran `docker build -t mcp/puppeteer -f src/puppeteer/Dockerfile .` and then I configured my `config.yaml` as:

```yaml
hostname: "0.0.0.0"  # Listen on all interfaces by default
port: 3056

debug:
  level: "info"

servers:
 puppeteer:
    command: docker
    args:
      - run
      - -i
      - --rm
      - --init
      - -e
      - DOCKER_CONTAINER=true
      - mcp/puppeteer
```

My `librechat.yaml` is:

```yaml

mcpServers:
  puppeteer:
    url: http://host.docker.internal:3056/puppeteer
```

And I also had to solve the issue of firewall, which was dropping packets from my docker bridge network.

```shell
sudo iptables -A INPUT -p tcp -s 172.18.0.0/16 --dport 3056 -j ACCEPT
```

I can now take SS and do everything else using Librechat Agents.
