### ISSUE TITLE
Suggestion : add env in server definition

### ISSUE THREAD

**Issue by PheelTi** [acehoss/mcp-gateway#5]
Hello, thank you for this great gateway.

This could be interesting to add en 'env' definition in your config. For instance : 
```yaml
servers:
  dummytool1:
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/dymmy-tool"
    env:
      MY_ENV_VAR: 1
  dummytool2:
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/dymmy-tool"
    env:
      MY_ENV_VAR: 2
```
And set them dyamically per server.
You could pass them like : 

```typescript
   const stdio = new StdioClientTransport({
      command: serverConfig.command,
      args: serverConfig.args,
      env: mergeEnvVars(process.env, serverConfig.env) as Record<string, string>
    });

```
