### ISSUE TITLE
Supports Docker command

### ISSUE THREAD

**Issue by davidfungf** [acehoss/mcp-gateway#6]
May I know does it support docker command? I ran the following configuration in Chainlit without success.

```
slack:
    command: docker
    args:
      - run
      - -i
      - --rm
      - -e
      - "SLAC_BOT_TOKEN"
      - -e
      - "SLACK_TEAM_ID"
      - "mcp/slack"
    env:
      SLACK_BOT_TOKEN: xxyxR
      SLACK_TEAM_ID: xyzL

```
